/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ItemPriceWatchSpecApplyConfiguration represents a declarative configuration of the ItemPriceWatchSpec type for use
// with apply.
//
// ItemPriceWatchSpec defines the desired state of ItemPriceWatch.
type ItemPriceWatchSpecApplyConfiguration struct {
	// ItemSlug is the URL-friendly item identifier used by the Warframe Market API
	// (e.g. "ash_prime_set"). It serves as the primary key for looking up orders.
	ItemSlug *string `json:"itemSlug,omitempty"`
	// Threshold is the platinum price at or below which a notification is sent.
	Threshold *int `json:"threshold,omitempty"`
	// NotificationWindow restricts notifications to a specific time range each day.
	NotificationWindow *NotificationWindowApplyConfiguration `json:"notificationWindow,omitempty"`
}

// ItemPriceWatchSpecApplyConfiguration constructs a declarative configuration of the ItemPriceWatchSpec type for use with
// apply.
func ItemPriceWatchSpec() *ItemPriceWatchSpecApplyConfiguration {
	return &ItemPriceWatchSpecApplyConfiguration{}
}

// WithItemSlug sets the ItemSlug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ItemSlug field is set to the value of the last call.
func (b *ItemPriceWatchSpecApplyConfiguration) WithItemSlug(value string) *ItemPriceWatchSpecApplyConfiguration {
	b.ItemSlug = &value
	return b
}

// WithThreshold sets the Threshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Threshold field is set to the value of the last call.
func (b *ItemPriceWatchSpecApplyConfiguration) WithThreshold(value int) *ItemPriceWatchSpecApplyConfiguration {
	b.Threshold = &value
	return b
}

// WithNotificationWindow sets the NotificationWindow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotificationWindow field is set to the value of the last call.
func (b *ItemPriceWatchSpecApplyConfiguration) WithNotificationWindow(value *NotificationWindowApplyConfiguration) *ItemPriceWatchSpecApplyConfiguration {
	b.NotificationWindow = value
	return b
}
