/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ItemPriceWatchStatusApplyConfiguration represents a declarative configuration of the ItemPriceWatchStatus type for use
// with apply.
//
// ItemPriceWatchStatus defines the observed state of ItemPriceWatch.
type ItemPriceWatchStatusApplyConfiguration struct {
	// CheapestPrice is the lowest platinum price found among the top sell orders.
	CheapestPrice *int `json:"cheapestPrice,omitempty"`
	// NotifiedOrderID is the order ID of the cheapest seller for which a notification
	// was last sent. It is cleared when that seller goes offline, so that a re-notification
	// is triggered when they come back online.
	NotifiedOrderID *string `json:"notifiedOrderId,omitempty"`
	// LastNotifiedAt is the timestamp of the last sent notification.
	LastNotifiedAt *v1.Time `json:"lastNotifiedAt,omitempty"`
	// Conditions represent the latest available observations of the ItemPriceWatch state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ItemPriceWatchStatusApplyConfiguration constructs a declarative configuration of the ItemPriceWatchStatus type for use with
// apply.
func ItemPriceWatchStatus() *ItemPriceWatchStatusApplyConfiguration {
	return &ItemPriceWatchStatusApplyConfiguration{}
}

// WithCheapestPrice sets the CheapestPrice field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CheapestPrice field is set to the value of the last call.
func (b *ItemPriceWatchStatusApplyConfiguration) WithCheapestPrice(value int) *ItemPriceWatchStatusApplyConfiguration {
	b.CheapestPrice = &value
	return b
}

// WithNotifiedOrderID sets the NotifiedOrderID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotifiedOrderID field is set to the value of the last call.
func (b *ItemPriceWatchStatusApplyConfiguration) WithNotifiedOrderID(value string) *ItemPriceWatchStatusApplyConfiguration {
	b.NotifiedOrderID = &value
	return b
}

// WithLastNotifiedAt sets the LastNotifiedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastNotifiedAt field is set to the value of the last call.
func (b *ItemPriceWatchStatusApplyConfiguration) WithLastNotifiedAt(value v1.Time) *ItemPriceWatchStatusApplyConfiguration {
	b.LastNotifiedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ItemPriceWatchStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ItemPriceWatchStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
