/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NotificationWindowApplyConfiguration represents a declarative configuration of the NotificationWindow type for use
// with apply.
//
// NotificationWindow defines a daily time range during which notifications are allowed.
type NotificationWindowApplyConfiguration struct {
	// From is the start of the window in "HH:MM" format (e.g. "10:00").
	From *string `json:"from,omitempty"`
	// To is the end of the window in "HH:MM" format (e.g. "18:00").
	To *string `json:"to,omitempty"`
}

// NotificationWindowApplyConfiguration constructs a declarative configuration of the NotificationWindow type for use with
// apply.
func NotificationWindow() *NotificationWindowApplyConfiguration {
	return &NotificationWindowApplyConfiguration{}
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *NotificationWindowApplyConfiguration) WithFrom(value string) *NotificationWindowApplyConfiguration {
	b.From = &value
	return b
}

// WithTo sets the To field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the To field is set to the value of the last call.
func (b *NotificationWindowApplyConfiguration) WithTo(value string) *NotificationWindowApplyConfiguration {
	b.To = &value
	return b
}
