/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RivenPriceWatchStatusApplyConfiguration represents a declarative configuration of the RivenPriceWatchStatus type for use
// with apply.
//
// RivenPriceWatchStatus defines the observed state of RivenPriceWatch.
type RivenPriceWatchStatusApplyConfiguration struct {
	// CheapestPrice is the lowest platinum price found among matching auctions.
	CheapestPrice *int `json:"cheapestPrice,omitempty"`
	// BestRollQuality is the average roll quality of the cheapest matching auction.
	BestRollQuality *int `json:"bestRollQuality,omitempty"`
	// NotifiedAuctionIDs tracks auction IDs for which a notification has already been sent.
	// This prevents duplicate notifications across reconcile cycles.
	NotifiedAuctionIDs []string `json:"notifiedAuctionIds,omitempty"`
	// LastNotifiedAt is the timestamp of the last sent notification.
	LastNotifiedAt *v1.Time `json:"lastNotifiedAt,omitempty"`
	// Conditions represent the latest available observations of the RivenPriceWatch state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RivenPriceWatchStatusApplyConfiguration constructs a declarative configuration of the RivenPriceWatchStatus type for use with
// apply.
func RivenPriceWatchStatus() *RivenPriceWatchStatusApplyConfiguration {
	return &RivenPriceWatchStatusApplyConfiguration{}
}

// WithCheapestPrice sets the CheapestPrice field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CheapestPrice field is set to the value of the last call.
func (b *RivenPriceWatchStatusApplyConfiguration) WithCheapestPrice(value int) *RivenPriceWatchStatusApplyConfiguration {
	b.CheapestPrice = &value
	return b
}

// WithBestRollQuality sets the BestRollQuality field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BestRollQuality field is set to the value of the last call.
func (b *RivenPriceWatchStatusApplyConfiguration) WithBestRollQuality(value int) *RivenPriceWatchStatusApplyConfiguration {
	b.BestRollQuality = &value
	return b
}

// WithNotifiedAuctionIDs adds the given value to the NotifiedAuctionIDs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NotifiedAuctionIDs field.
func (b *RivenPriceWatchStatusApplyConfiguration) WithNotifiedAuctionIDs(values ...string) *RivenPriceWatchStatusApplyConfiguration {
	for i := range values {
		b.NotifiedAuctionIDs = append(b.NotifiedAuctionIDs, values[i])
	}
	return b
}

// WithLastNotifiedAt sets the LastNotifiedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastNotifiedAt field is set to the value of the last call.
func (b *RivenPriceWatchStatusApplyConfiguration) WithLastNotifiedAt(value v1.Time) *RivenPriceWatchStatusApplyConfiguration {
	b.LastNotifiedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RivenPriceWatchStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *RivenPriceWatchStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
