/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RivenPriceWatchSpecApplyConfiguration represents a declarative configuration of the RivenPriceWatchSpec type for use
// with apply.
//
// RivenPriceWatchSpec defines the desired state of RivenPriceWatch.
type RivenPriceWatchSpecApplyConfiguration struct {
	// WeaponSlug is the URL-friendly weapon identifier (e.g. "falcor", "gram_prime").
	WeaponSlug *string `json:"weaponSlug,omitempty"`
	// PositiveStats lists the required positive stat url_names
	// (e.g. ["critical_chance", "critical_damage"]).
	PositiveStats []string `json:"positiveStats,omitempty"`
	// NegativeStats controls the negative stat filter:
	// "" = any, "has" = must have one, "none" = no negative, or a specific stat url_name.
	NegativeStats *string `json:"negativeStats,omitempty"`
	// MaxReRolls limits results to rivens with at most this many re-rolls. 0 means no limit.
	MaxReRolls *int `json:"maxReRolls,omitempty"`
	// PlayerStatus filters auctions by seller online status.
	// Valid values: ingame, online, offline. Defaults to [ingame, online] if not set.
	PlayerStatus []string `json:"playerStatus,omitempty"`
	// MinRollQuality is the minimum average roll quality (0–100%) required across
	// positive stats for a notification to be sent.
	MinRollQuality *int `json:"minRollQuality,omitempty"`
	// BuyoutOnly restricts results to direct-sell auctions, excluding bidding-only listings.
	BuyoutOnly *bool `json:"buyoutOnly,omitempty"`
	// Threshold is the platinum price at or below which a notification is sent.
	Threshold *int `json:"threshold,omitempty"`
	// NotificationWindow restricts notifications to a specific time range each day.
	NotificationWindow *NotificationWindowApplyConfiguration `json:"notificationWindow,omitempty"`
}

// RivenPriceWatchSpecApplyConfiguration constructs a declarative configuration of the RivenPriceWatchSpec type for use with
// apply.
func RivenPriceWatchSpec() *RivenPriceWatchSpecApplyConfiguration {
	return &RivenPriceWatchSpecApplyConfiguration{}
}

// WithWeaponSlug sets the WeaponSlug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WeaponSlug field is set to the value of the last call.
func (b *RivenPriceWatchSpecApplyConfiguration) WithWeaponSlug(value string) *RivenPriceWatchSpecApplyConfiguration {
	b.WeaponSlug = &value
	return b
}

// WithPositiveStats adds the given value to the PositiveStats field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PositiveStats field.
func (b *RivenPriceWatchSpecApplyConfiguration) WithPositiveStats(values ...string) *RivenPriceWatchSpecApplyConfiguration {
	for i := range values {
		b.PositiveStats = append(b.PositiveStats, values[i])
	}
	return b
}

// WithNegativeStats sets the NegativeStats field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NegativeStats field is set to the value of the last call.
func (b *RivenPriceWatchSpecApplyConfiguration) WithNegativeStats(value string) *RivenPriceWatchSpecApplyConfiguration {
	b.NegativeStats = &value
	return b
}

// WithMaxReRolls sets the MaxReRolls field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReRolls field is set to the value of the last call.
func (b *RivenPriceWatchSpecApplyConfiguration) WithMaxReRolls(value int) *RivenPriceWatchSpecApplyConfiguration {
	b.MaxReRolls = &value
	return b
}

// WithPlayerStatus adds the given value to the PlayerStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PlayerStatus field.
func (b *RivenPriceWatchSpecApplyConfiguration) WithPlayerStatus(values ...string) *RivenPriceWatchSpecApplyConfiguration {
	for i := range values {
		b.PlayerStatus = append(b.PlayerStatus, values[i])
	}
	return b
}

// WithMinRollQuality sets the MinRollQuality field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinRollQuality field is set to the value of the last call.
func (b *RivenPriceWatchSpecApplyConfiguration) WithMinRollQuality(value int) *RivenPriceWatchSpecApplyConfiguration {
	b.MinRollQuality = &value
	return b
}

// WithBuyoutOnly sets the BuyoutOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BuyoutOnly field is set to the value of the last call.
func (b *RivenPriceWatchSpecApplyConfiguration) WithBuyoutOnly(value bool) *RivenPriceWatchSpecApplyConfiguration {
	b.BuyoutOnly = &value
	return b
}

// WithThreshold sets the Threshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Threshold field is set to the value of the last call.
func (b *RivenPriceWatchSpecApplyConfiguration) WithThreshold(value int) *RivenPriceWatchSpecApplyConfiguration {
	b.Threshold = &value
	return b
}

// WithNotificationWindow sets the NotificationWindow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotificationWindow field is set to the value of the last call.
func (b *RivenPriceWatchSpecApplyConfiguration) WithNotificationWindow(value *NotificationWindowApplyConfiguration) *RivenPriceWatchSpecApplyConfiguration {
	b.NotificationWindow = value
	return b
}
