---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - warframe.market
  resources:
  - pricewatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - warframe.market
  resources:
  - pricewatches/finalizers
  verbs:
  - update
- apiGroups:
  - warframe.market
  resources:
  - pricewatches/status
  verbs:
  - get
  - patch
  - update
