---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - warframe.market
  resources:
  - itempricewatches
  - rivenpricewatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - warframe.market
  resources:
  - itempricewatches/finalizers
  - rivenpricewatches/finalizers
  verbs:
  - update
- apiGroups:
  - warframe.market
  resources:
  - itempricewatches/status
  - rivenpricewatches/status
  verbs:
  - get
  - patch
  - update
