apiVersion: warframe.market/v1alpha1
kind: RivenPriceWatch
metadata:
  labels:
    app.kubernetes.io/name: warframe-market-operator
    app.kubernetes.io/managed-by: kustomize
  name: falcor-riven
spec:
  weaponSlug: falcor
  maxReRolls: 1
  threshold: 20
  buyoutOnly: true
  notificationWindow:
    from: "08:00"
    to: "22:00"
