## Append samples of your project ##
resources:
- v1alpha1_pricewatch.yaml
- v1alpha1_itempricewatch.yaml
- _v1alpha1_itempricewatch.yaml
- v1alpha1_rivenpricewatch.yaml
- _v1alpha1_rivenpricewatch.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
