apiVersion: warframe.market/v1alpha1
kind: PriceWatch
metadata:
  labels:
    app.kubernetes.io/name: warframe-market-operator
    app.kubernetes.io/managed-by: kustomize
  name: primed-firestorm
spec:
  itemSlug: primed_firestorm
  threshold: 40
  notificationWindow:
    from: "08:00"
    to: "22:00"
