apiVersion: warframe.market/v1alpha1
kind: RivenPriceWatch
metadata:
  labels:
    app.kubernetes.io/name: warframe-market-operator
    app.kubernetes.io/managed-by: kustomize
  name: rivenpricewatch-sample
spec:
  # TODO(user): Add fields here
