//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPriceWatch) DeepCopyInto(out *ItemPriceWatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPriceWatch.
func (in *ItemPriceWatch) DeepCopy() *ItemPriceWatch {
	if in == nil {
		return nil
	}
	out := new(ItemPriceWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ItemPriceWatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPriceWatchList) DeepCopyInto(out *ItemPriceWatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ItemPriceWatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPriceWatchList.
func (in *ItemPriceWatchList) DeepCopy() *ItemPriceWatchList {
	if in == nil {
		return nil
	}
	out := new(ItemPriceWatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ItemPriceWatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPriceWatchSpec) DeepCopyInto(out *ItemPriceWatchSpec) {
	*out = *in
	if in.NotificationWindow != nil {
		in, out := &in.NotificationWindow, &out.NotificationWindow
		*out = new(NotificationWindow)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPriceWatchSpec.
func (in *ItemPriceWatchSpec) DeepCopy() *ItemPriceWatchSpec {
	if in == nil {
		return nil
	}
	out := new(ItemPriceWatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPriceWatchStatus) DeepCopyInto(out *ItemPriceWatchStatus) {
	*out = *in
	if in.LastNotifiedAt != nil {
		in, out := &in.LastNotifiedAt, &out.LastNotifiedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPriceWatchStatus.
func (in *ItemPriceWatchStatus) DeepCopy() *ItemPriceWatchStatus {
	if in == nil {
		return nil
	}
	out := new(ItemPriceWatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationWindow) DeepCopyInto(out *NotificationWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationWindow.
func (in *NotificationWindow) DeepCopy() *NotificationWindow {
	if in == nil {
		return nil
	}
	out := new(NotificationWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RivenPriceWatch) DeepCopyInto(out *RivenPriceWatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RivenPriceWatch.
func (in *RivenPriceWatch) DeepCopy() *RivenPriceWatch {
	if in == nil {
		return nil
	}
	out := new(RivenPriceWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RivenPriceWatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RivenPriceWatchList) DeepCopyInto(out *RivenPriceWatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RivenPriceWatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RivenPriceWatchList.
func (in *RivenPriceWatchList) DeepCopy() *RivenPriceWatchList {
	if in == nil {
		return nil
	}
	out := new(RivenPriceWatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RivenPriceWatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RivenPriceWatchSpec) DeepCopyInto(out *RivenPriceWatchSpec) {
	*out = *in
	if in.PositiveStats != nil {
		in, out := &in.PositiveStats, &out.PositiveStats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PlayerStatus != nil {
		in, out := &in.PlayerStatus, &out.PlayerStatus
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotificationWindow != nil {
		in, out := &in.NotificationWindow, &out.NotificationWindow
		*out = new(NotificationWindow)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RivenPriceWatchSpec.
func (in *RivenPriceWatchSpec) DeepCopy() *RivenPriceWatchSpec {
	if in == nil {
		return nil
	}
	out := new(RivenPriceWatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RivenPriceWatchStatus) DeepCopyInto(out *RivenPriceWatchStatus) {
	*out = *in
	if in.NotifiedAuctionIDs != nil {
		in, out := &in.NotifiedAuctionIDs, &out.NotifiedAuctionIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastNotifiedAt != nil {
		in, out := &in.LastNotifiedAt, &out.LastNotifiedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RivenPriceWatchStatus.
func (in *RivenPriceWatchStatus) DeepCopy() *RivenPriceWatchStatus {
	if in == nil {
		return nil
	}
	out := new(RivenPriceWatchStatus)
	in.DeepCopyInto(out)
	return out
}
