name: CI

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Go tools
        run: just tools

      - name: Run tests
        run: just test

  test-e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Go tools
        run: just tools

      - name: Run e2e tests
        run: just test-e2e

